set -e
true
true
/opt/miniconda3/bin/spades-hammer /Users/markhsia/arctic_agents/report_final/assembly/SRR8813623_metaspades/corrected/configs/config.info
/Users/markhsia/arctic_agents/.venv/bin/python3 /opt/miniconda3/share/spades/spades_pipeline/scripts/compress_all.py --input_file /Users/markhsia/arctic_agents/report_final/assembly/SRR8813623_metaspades/corrected/corrected.yaml --ext_python_modules_home /opt/miniconda3/share/spades --max_threads 16 --output_dir /Users/markhsia/arctic_agents/report_final/assembly/SRR8813623_metaspades/corrected --gzip_output
true
true
/opt/miniconda3/bin/spades-core /Users/markhsia/arctic_agents/report_final/assembly/SRR8813623_metaspades/K21/configs/config.info /Users/markhsia/arctic_agents/report_final/assembly/SRR8813623_metaspades/K21/configs/mda_mode.info /Users/markhsia/arctic_agents/report_final/assembly/SRR8813623_metaspades/K21/configs/meta_mode.info
/opt/miniconda3/bin/spades-core /Users/markhsia/arctic_agents/report_final/assembly/SRR8813623_metaspades/K33/configs/config.info /Users/markhsia/arctic_agents/report_final/assembly/SRR8813623_metaspades/K33/configs/mda_mode.info /Users/markhsia/arctic_agents/report_final/assembly/SRR8813623_metaspades/K33/configs/meta_mode.info
/opt/miniconda3/bin/spades-core /Users/markhsia/arctic_agents/report_final/assembly/SRR8813623_metaspades/K55/configs/config.info /Users/markhsia/arctic_agents/report_final/assembly/SRR8813623_metaspades/K55/configs/mda_mode.info /Users/markhsia/arctic_agents/report_final/assembly/SRR8813623_metaspades/K55/configs/meta_mode.info
/Users/markhsia/arctic_agents/.venv/bin/python3 /opt/miniconda3/share/spades/spades_pipeline/scripts/copy_files.py /Users/markhsia/arctic_agents/report_final/assembly/SRR8813623_metaspades/K55/before_rr.fasta /Users/markhsia/arctic_agents/report_final/assembly/SRR8813623_metaspades/before_rr.fasta /Users/markhsia/arctic_agents/report_final/assembly/SRR8813623_metaspades/K55/assembly_graph_after_simplification.gfa /Users/markhsia/arctic_agents/report_final/assembly/SRR8813623_metaspades/assembly_graph_after_simplification.gfa /Users/markhsia/arctic_agents/report_final/assembly/SRR8813623_metaspades/K55/final_contigs.fasta /Users/markhsia/arctic_agents/report_final/assembly/SRR8813623_metaspades/contigs.fasta /Users/markhsia/arctic_agents/report_final/assembly/SRR8813623_metaspades/K55/first_pe_contigs.fasta /Users/markhsia/arctic_agents/report_final/assembly/SRR8813623_metaspades/first_pe_contigs.fasta /Users/markhsia/arctic_agents/report_final/assembly/SRR8813623_metaspades/K55/strain_graph.gfa /Users/markhsia/arctic_agents/report_final/assembly/SRR8813623_metaspades/strain_graph.gfa /Users/markhsia/arctic_agents/report_final/assembly/SRR8813623_metaspades/K55/scaffolds.fasta /Users/markhsia/arctic_agents/report_final/assembly/SRR8813623_metaspades/scaffolds.fasta /Users/markhsia/arctic_agents/report_final/assembly/SRR8813623_metaspades/K55/scaffolds.paths /Users/markhsia/arctic_agents/report_final/assembly/SRR8813623_metaspades/scaffolds.paths /Users/markhsia/arctic_agents/report_final/assembly/SRR8813623_metaspades/K55/assembly_graph_with_scaffolds.gfa /Users/markhsia/arctic_agents/report_final/assembly/SRR8813623_metaspades/assembly_graph_with_scaffolds.gfa /Users/markhsia/arctic_agents/report_final/assembly/SRR8813623_metaspades/K55/assembly_graph.fastg /Users/markhsia/arctic_agents/report_final/assembly/SRR8813623_metaspades/assembly_graph.fastg /Users/markhsia/arctic_agents/report_final/assembly/SRR8813623_metaspades/K55/final_contigs.paths /Users/markhsia/arctic_agents/report_final/assembly/SRR8813623_metaspades/contigs.paths
true
/Users/markhsia/arctic_agents/.venv/bin/python3 /opt/miniconda3/share/spades/spades_pipeline/scripts/breaking_scaffolds_script.py --result_scaffolds_filename /Users/markhsia/arctic_agents/report_final/assembly/SRR8813623_metaspades/scaffolds.fasta --misc_dir /Users/markhsia/arctic_agents/report_final/assembly/SRR8813623_metaspades/misc --threshold_for_breaking_scaffolds 3
true
